services:

  # -------------------- ZOOKEEPER --------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # -------------------- KAFKA --------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # -------------------- MYSQL --------------------
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: airline_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # -------------------- EUREKA --------------------
  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    volumes:
      - ./logs/eureka-service:/app/logs

  # -------------------- API GATEWAY --------------------
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    volumes:
      - ./logs/api-gateway:/app/logs
    depends_on:
      - eureka-service

  # -------------------- FLIGHT SERVICE --------------------
  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8081:8081"
    volumes:
      - ./logs/flight-service:/app/logs
    depends_on:
      - kafka
      - mysql
      - eureka-service

  # -------------------- BOOKING SERVICE --------------------
  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8084:8084"
    volumes:
      - ./logs/booking-service:/app/logs
    depends_on:
      - kafka
      - mysql
      - eureka-service

  # -------------------- EMAIL SERVICE --------------------
  email-service:
    build: ./email-service
    container_name: email-service
    ports:
      - "8185:8185"
    volumes:
      - ./logs/email-service:/app/logs
    depends_on:
      - kafka
      - eureka-service 
  
  # -------------------- AUTH SERVICE --------------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8543:8543"
    volumes:
      - ./logs/auth-service:/app/logs
    depends_on:
      - mysql
      - eureka-service


volumes:
  mysql_data:
